version: '3'
services:
  web:
    build:
      context: docker
      dockerfile: web.dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 90:80
    depends_on:
      - php
  php:
    build:
      context: docker
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www/html