title: Services
fields:
  -
    handle: services_image
    field:
      mode: grid
      container: images
      restrict: true
      allow_uploads: true
      max_files: 1
      display: 'Services Image'
      type: assets
      icon: assets
      listable: hidden
